name: "Sanity Check Trigger"
on:
  workflow_dispatch:

jobs:
  inject-develocity:
    env:
      DEVELOCITY_INJECTION_ENABLED: true
      DEVELOCITY_URL: https://ge-helm-cluster-unstable.grdev.net/
      DEVELOCITY_PLUGIN_VERSION: '3.17.3'
      DEVELOCITY_CCUD_PLUGIN_VERSION: '2.0'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@57a78b183d00d4e4706c35653fff0f4c6492d4dd
      with:
        develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    - name: Run Gradle build
      id: gradle
      run: ./gradlew help
    - name: Check Short Lived Token
      run: echo "Is it a token ? ${#DEVELOCITY_ACCESS_KEY}"
